name: CI - Master

on:
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #
      # ... your other steps, such as running tests, etc...
      #
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
          sudo chmod 600 ~/.ssh/deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      # (optional - only needed if your config uses environment variables)
      - name: Create env file
        run: |
          echo "$TEST_ENV_VARS" > .env
        shell: bash
        env:
          TEST_ENV_VARS: ${{secrets.TEST_ENV_VARS}}

      - name: Create credentials file
        run: |
          echo "$SERVICE_ACCOUNT_CREDENTIALS" > .env
        shell: bash
        env:
          SERVICE_ACCOUNT_CREDENTIALS: ${{secrets.SERVICE_ACCOUNT_CREDENTIALS}}
          
      # - name: Install PM2
      #   run: npm i pm2

      - name: Deploy
        run: |
          chmod +x ./pm2script.sh
          bash ./pm2script.sh
        # Or alternately, put this deploy script in your package.json's scripts and run it using yarn/npm:
        # run: yarn deploy