name: CI - Master

on:
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          envs: TEST_ENV_VARS, SERVICE_ACCOUNT_CREDENTIALS
          script: |
            cd github/deutsche-bank-2-google-sheets
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            git fetch
            git pull
            git status
            echo "$TEST_ENV_VARS" > .env
            echo "$SERVICE_ACCOUNT_CREDENTIALS" > credentials.json
            ls -la
            pip3 install -r requirements.txt
            npm i -g pm2
            pm2 restart "FinanceBot"
            cat .env
            cat credentials.json
        env:
          TEST_ENV_VARS: ${{secrets.TEST_ENV_VARS}}
          SERVICE_ACCOUNT_CREDENTIALS: ${{secrets.SERVICE_ACCOUNT_CREDENTIALS}}
